version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgresql://postgres:admin@db:5432/projeto
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projeto
    volumes:
      - ./projeto.sql:/docker-entrypoint-initdb.d/projeto.sql

