# version: "3.9"
# services:
#   frontend:
#     build: ./client
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#   backend:
#     build: ./api
#     ports:
#       - "3001:3001"
#     environment:
#       DB_URL: postgresql://postgres:admin@db:5432/projeto
#     depends_on:
#       - db
#   db:
#     build: .
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: projeto

# version: '3'

# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: projeto
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     restart: always

#   backend:
#     build: ./api
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://postgres:admin@db-1:5432/projeto
#     ports:
#       - "3001:3001"
#     restart: always

#   frontend:
#     build: ./client
#     ports:
#       - "3000:3000"
#     restart: always

# volumes:
#   postgres-data:

version: "3.9"
services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projeto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d projeto -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgresql://postgres:admin@db:5432/projeto
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  